### ISSUE TITLE
Android flavors not compiling

### ISSUE THREAD

**Issue by petetastic** [maxkomarychev/react-native-ultimate-config#24]
Hi there,
XCode Schemes work great. But I'm now trying to get the Android flavors working but they aren't compiling.

android/app/build.gradle:
```
project.ext.flavorEnvMapping = [
    local: "../env.local.yaml"
]
android {
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    flavorDimensions "default"
    productFlavors {
       local {}
   }
}
```

I can then run:
`yarn rnuc env.local.yaml`
with no problem.

But then I get this:
```
cd android
./gradlew assembleLocalDebug

> Configure project :app
Flavor mapping detected: [local:../env.local.yaml]
Root config [local:APP_VERSION:1 FACEBOOK_APP_ID:12345]
processing variant localDebug
mapping exists

FAILURE: Build failed with an exception.

* Where:
Script '/Users/xxxxx/Dropbox/PROJECTS/AUPAIRED/RCT/xxxxx/node_modules/react-native-ultimate-config/android/rnuc.gradle' line: 44

* What went wrong:
A problem occurred configuring project ':app'.
> groovy.lang.MissingMethodException: No signature of method: rnuc_b2ienkmadhxj28kgl9iu86xug$_flattenConfig_closure3.doCall() is applicable for argument types: (String) values: [A]
  Possible solutions: doCall(java.lang.Object, java.lang.Object), findAll(), findAll(), isCase(java.lang.Object), isCase(java.lang.Object)
```

Any thoughts?

Thanks,

Pete

**Comment by maxkomarychev** [comment]
@petetastic which version of the library are you using? can you please share content of this file you are referring to in the mapping `env.local.yaml` ?

**Comment by maxkomarychev** [comment]
btw, running `yarn rnuc env.local.yaml` is redundant if you're using cookbook's flavor-based integration.

**Comment by petetastic** [comment]
Hi there, I'm using the latest version I think (3.1.2).

My env.local.yaml looks something like:

```
APP_VERSION:1
API_ROOT:https://my.example.com
API_VERSION:v2
USER_IMG_DIR:https://my.example.com/images/user
WEB_ROOT:https://my.example.com
FACEBOOK_APP_ID:12345
FACEBOOK_APP_ID_FB:12345
```

**Comment by maxkomarychev** [comment]
hey @petetastic  I just dupmed your sample and run e2e with it. this yaml is malformed, syntax requires a space between colon and value `APP_VERSION:1` vs `APP_VERSION: 1`

here's the error I'm getting with your sampleconfig. https://github.com/maxkomarychev/react-native-ultimate-config/pull/25/checks?check_run_id=802475988 it's exactly the same as

**Comment by maxkomarychev** [comment]
to recap

1. using flavor(scheme)-based integration and running `yarn rnuc...` are mutually exclusive. don't do `yarn rnuc...` if you use schemes/flavors
2. yaml you have pasted earlier has invalid syntax. it's treated as a single string instead of being object with fields
3. even if ios has compiled properly I have doubts it has proper values at runtime, have you been able to confirm these values were non-empty?

**Comment by petetastic** [comment]
Thanks so much Max. I literally arrived at the same conclusion as you at the exact same time. My fault entirely as I've never worked with YAML. That pesky space!

Anyway it looks to be all sorted at the moment. Since it's an easy gotcha and people might get caught on it, is there a way to raise a nice error to show that the YAML file has not compiled properly? For noobs like me that might have pointed me in the right direction sooner. Looking at their code the Snake Yaml library can throw exceptions.

Cheers

**Comment by maxkomarychev** [comment]
> is there a way to raise a nice error to show that the YAML file has not compiled properly

looks like a good idea, let me think about it. I need to double check why didn't raise any errors when doing `yarn rnuc ...`
I suspect this is due to the fact that yaml lib treated content of a file as a string (which is kind of correct yaml per se but not what react-native-ultimate-config expects).

**Comment by maxkomarychev** [comment]
> Looking at their code the Snake Yaml library can throw exceptions.

after a bit more digging, that yaml is technically correct from library perspective, the application-level is not correct - it read string instead of object and the exception was thrown down the pipe where it tried to iterate strings as if it was an object. so `react-native-ultimate-config` have to detect this kind of troubles expelicitly

**Comment by maxkomarychev** [comment]
I added a bit more meaningful validation in https://github.com/maxkomarychev/react-native-ultimate-config/pull/26
closing this one, thanks for feedback!
