### ISSUE TITLE
Is part of README redundant?

### ISSUE THREAD

**Issue by grubstarstar** [maxkomarychev/react-native-ultimate-config#5]
In the docs it says these files will be updated:

```
android/src/main/java/com/reactnativeultimateconfig/ConfigValues.java
ios/ConfigValues.h
```

but they don't seem to exist in my project and yet the config seems to work fine. Is this part of the README now redundant?

**Comment by grubstarstar** [comment]
Oh I just realised this is in the root of the react-native-ultimate-config module itself, not my project.

In which case, where should I run `git update-index --assume-unchanged android/src/main/java/com/reactnativeultimateconfig/ConfigValues.java ios/ConfigValues.h` from? From within `node_module/react-native-ultimate-config`?

**Comment by maxkomarychev** [comment]
hey @grubstarstar ! 

this part of README is relevant in case if you're developing library itself, it's not needed when you just use it, please refer to [api](https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/docs/quickstart.md) and [quickstart](https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/docs/quickstart.md) docs for usage tips

sorry for confusion, I guess I'd need to put that part under more clear title

**Comment by maxkomarychev** [comment]
> Just trying to clarify what this achieves.

these files I mentioned are being codegenerated and overwritten constantly when developing and testing a library, therefore when I'm in dev cycle I mark these files as "unchanged" so that they do not appear in my git diff and I don't commit them by accident. gitignore does not help here because I do need these files to be in repo but at the same time I only need them to be updated whenever I explicitly mark them to

**Comment by grubstarstar** [comment]
Ah that makes sense! Thanks for the quick response. The module worked a treat on both iOS and Android 🙂
